name: newsone
description: My First News app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.1.3
  hive: ^2.2.3
  http: ^0.13.5
  hydrated_bloc: ^9.1.0
  # intl: ^0.18.0
  share_plus: ^6.3.1
  shimmer: ^2.0.0
  transition: ^2.0.2
  url_launcher: ^6.1.9
  webview_flutter: ^4.1.0
  webview_flutter_android: ^3.3.0
  webview_flutter_wkwebview: ^3.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  intl: 0.17.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"


flutter:
  uses-material-design: true
  generate: true

  # assets:
  # To add assets to your application, add an assets section, like this:
  assets:
    # - images/a_dot_burr.jpeg
    - images/dotted-placeholder.jpg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
